# Generated by Django 5.1.3 on 2024-11-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
