# Generated by Django 5.1.3 on 2024-11-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_faqs_answer_alter_faqs_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'ordering': ['date_asked'], 'verbose_name': 'FAQS', 'verbose_name_plural': 'FAQS'},
        ),
        migrations.AddField(
            model_name='contact',
            name='has_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='save_to',
            field=models.CharField(choices=[('phone', 'Phone'), ('sim', 'Sim'), ('email', 'Email')], default='phone', max_length=250, null=True),
        ),
    ]
