# Generated by Django 5.1.2 on 2024-10-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_due',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
