# Generated by Django 5.1.2 on 2024-10-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_is_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_due',
        ),
    ]
