# Generated by Django 5.1.2 on 2024-10-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todo_is_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_due',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
